In [8]:
import math
import numpy as np

import torch
import torchvision
from torch.utils.data import DataLoader, Dataset
import torch.nn as nn

from sklearn import datasets
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import f1_score, roc_auc_score

import matplotlib.pyplot as plt
from torch.utils.data.dataset import T_co

gpu = torch.cuda.current_device()
torch.cuda.get_device_name()

'NVIDIA GeForce GTX 1650 with Max-Q Design'

In [11]:
def softmax(x):
    return np.exp(x) / np.sum(np.exp(x), axis=0)

x = np.array([1,2,3])

softmax(x)

# highest values have high probability

array([0.09003057, 0.24472847, 0.66524096])

In [14]:
# torch
x = torch.tensor([1,2,3], dtype=torch.float32)

torch.softmax(x, dim=0)

tensor([0.0900, 0.2447, 0.6652])

In [22]:
# cross entropy
loss = nn.CrossEntropyLoss()

# suppose we have 1 sample and 3 possible classes (0, 1 and 2)
# n_samples x n_classes = 1 x 3
y = torch.tensor([0])
y_predicted_good = torch.tensor([[2.0, 1.0, 0.1]])
y_predicted_bad = torch.tensor([[0.5, 2.0, 0.3]])

l1 = loss(y_predicted_good, y)
l2 = loss(y_predicted_bad, y)

print(l1)
print(l2)

# good prediction has low cross entropy loss

# to get good / bad prediction labels
_, prediction_label_good = torch.max(y_predicted_good, dim=1)
_, prediction_label_bad = torch.max(y_predicted_bad, dim=1)
# torch.max() returns both the maximum value and their index -> in this case index is the label value

print(prediction_label_good)
print(prediction_label_bad)

# when using cross entropy loss, do not use softmax layer in the end

tensor(0.4170)
tensor(1.8406)
tensor([0])
tensor([1])


In [ ]:
# a sample net

class MyNeuralNet(nn.Module):

    def __init__(self, input_size, hidden_size):
        super(MyNeuralNet, self).__init__()
        self.linear1 = nn.Linear(input_size, hidden_size)
        self.relu = nn.ReLU()
        self.linear2 = nn.Linear(hidden_size, 1)
        # in end size=1 because this is a binary classifier
        # if it is a 3 class classifier, output size would be 3 -> or num_classes

    def forward(self, x):
        out = self.linear1(x)
        out = self.relu(out)
        out = self.linear2(out)

        # sigmoid in the end
        y_pred = torch.sigmoid_(out)
        return y_pred

model = MyNeuralNet(input_size=28*28, hidden_size=5)
criterion = nn.BCELoss()
