In [120]:
import torch
import numpy as np

gpu = torch.cuda.current_device()
torch.cuda.get_device_name()

'NVIDIA GeForce GTX 1650 with Max-Q Design'

Torch Basics

In [87]:
torch.empty(2, 2, 1)
# 2 in x-axis, 2 y-axis, 2 z-axis

tensor([[[9.1477e-41],
         [0.0000e+00]],

        [[1.1210e-44],
         [0.0000e+00]]])

In [88]:
# select nums from uniform distribution
torch.rand(3, 4)

tensor([[0.6760, 0.1192, 0.7399, 0.0727],
        [0.0616, 0.5516, 0.2726, 0.8767],
        [0.5714, 0.9649, 0.1133, 0.8203]])

In [89]:
torch.ones(20, dtype=torch.double)
# torch.int32
# torch.float16
# torch.double

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1.], dtype=torch.float64)

In [90]:
x = torch.zeros(10)

# get size
x.size()

torch.Size([10])

In [91]:
# create tensor from list
l = [1,2,3,4,5]
torch.tensor(l)

tensor([1, 2, 3, 4, 5])

In [92]:
# get range of values
torch.range(3, 40)

E:\OpenSoftware\miniconda\envs\ml_project\lib\site-packages\ipykernel_launcher.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  


tensor([ 3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14., 15., 16.,
        17., 18., 19., 20., 21., 22., 23., 24., 25., 26., 27., 28., 29., 30.,
        31., 32., 33., 34., 35., 36., 37., 38., 39., 40.])

In [93]:
x = torch.rand(2)
y = torch.rand(2)

x + y

tensor([1.8081, 1.0607])

In [94]:
# equivalent to y += x
y.add_(x)

# every func with trailing _ will do inplace operation
y.mul_(x)
y.sub_(x)
y.div_(x)


tensor([0.8081, 0.0607])

In [95]:
# slicing
x = torch.rand(5,3)
# 5 rows 3 columns

# select all rows and 0th column
x[:, 0]

tensor([0.0967, 0.3695, 0.3107, 0.4822, 0.9004])

In [96]:
# first row with all columns
x[1, :]

tensor([0.3695, 0.2639, 0.3966])

In [104]:
# return actual value if only one tensor is selected
x[1,1].item()

0.2639394998550415

In [108]:
x = torch.rand(4,4)

# flatten a 4x4 matrix to single list
# the size should match 4x4=16
x.view(16)

tensor([0.2568, 0.6811, 0.5752, 0.0833, 0.2946, 0.7234, 0.9751, 0.9227, 0.0502,
        0.5322, 0.8645, 0.4961, 0.3981, 0.0661, 0.6657, 0.7376])

In [118]:
# `-1` if I don't know exact value
# torch would automatically predict it
x.view(-1, 8)

tensor([[0.2568, 0.6811, 0.5752, 0.0833, 0.2946, 0.7234, 0.9751, 0.9227],
        [0.0502, 0.5322, 0.8645, 0.4961, 0.3981, 0.0661, 0.6657, 0.7376]])

Numpy

In [125]:
a = torch.ones(5)
a
b = a.numpy()
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [126]:
# be careful that if both torch and numpy use cpu
# then both point to same memory location
# then changes to a will affect b
a.add_(2)
b

array([3., 3., 3., 3., 3.], dtype=float32)

In [130]:
# vice versa

a = np.ones(5)

b = torch.from_numpy(a)
b
# same memory problem

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [131]:
# tells torch that this will need to calculate gradients beforehand
x = torch.ones(5, requires_grad=True)
x


tensor([1., 1., 1., 1., 1.], requires_grad=True)